# Generated by Django 5.2.1 on 2025-05-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_purchases_category_alter_product_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='price_total',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='sales',
            name='price_total',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12),
        ),
    ]
