# Generated by Django 5.2.1 on 2025-05-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_brand_image_alter_firm_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stock'),
        ),
        migrations.AlterField(
            model_name='firm',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stock'),
        ),
    ]
