# Generated by Django 5.2.1 on 2025-05-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_brand_image_alter_firm_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='brand'),
        ),
        migrations.AlterField(
            model_name='firm',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='firm'),
        ),
    ]
